title: CyberSecPath
tagline: "Exploring the depths of cybersecurity: Learn, Build, Secure."
description: A personal blog documenting my journey into cybersecurity, tech, and projects.
author: Your Name
theme: jekyll-theme-cayman  # or change to 'minimal', 'midnight', etc.

# Optional extras:
show_downloads: false
markdown: kramdown
