title: The Stack Journal
description: Exploring the depths of tech—code, security, and systems.
baseurl: "" # leave this empty if you're publishing to username.github.io
url: "https://rejeeshkoshy.github.io" # replace with your actual GitHub Pages URL

theme: minima
markdown: kramdown
permalink: pretty

# Plugins (optional, but useful)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: turn off markdown-based homepage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: null

# Navigation links (can be used if you want links at top)
header_pages:
  # Leave empty or comment out if you're using pure HTML landing
  # - blog.md
  # - projects.md

# Social links (optional metadata)
email: your@email.com
linkedin_username: yourlinkedin

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
