title: The Stack Journal
description: Exploring the depths of tech—code, security, and systems.
baseurl: "" 
url: "https://rejeeshkoshy.github.io"

theme: minima
markdown: kramdown
permalink: /:categories/:title/

collections:
  blog:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: default
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default

# Plugins 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
