title: The Stack Journal
description: Exploring the depths of tech—code, security, and systems.
theme: minima
baseurl: "" # leave empty for user.github.io repo, else set as "/repo-name"
url: "https://yourusername.github.io"

markdown: kramdown
permalink: pretty

# Navigation links
header_pages:
  - index.md

# Social links (optional)
email: your@email.com
linkedin_username: yourlinkedin

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
