title: The Stack Journal
description: Exploring the depths of tech—code, security, and systems.
theme: minima
baseurl: "" 
url: "https://rejeeshkoshy.github.io"

markdown: kramdown
permalink: pretty

# Navigation links
header_pages:
  - index.md

# Social links 
email: rejeeshkoshy10@email.com
linkedin_username: Rejeesh Koshy

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
